version: 0.2

phases:
   setup-java:
      runtime-versions:
           java: corretto17
    
    Install:
      commands:
           - mvn clean install

    Build:
      commands:
           - mvn package

Artifacts:
   files:
     - 'target/*.jar'
   name: myBuildArtifact