version: 0.2
env:
  parameter-store:
       My_Param: "My_Param"
       Name: "Name"
phases:
   install: 
       runtime-versions:
           java: corretto17

   build: 
     commands:
         - mvn clean install -DskipTests
         - echo "The Value Of Parameter is $My_Param"
         - echo "My Name Is = $Name"
