name: AWS OIDC Authentication

on:
  push:
    branches: [ main ]

# CRITICAL: These permissions are required to request the OIDC JWT token
permissions:
  id-token: write
  contents: read

jobs:
  aws-connect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::102512866166:role/AWS-Oidc-GitHub_Actions
          aws-region: us-east-2 # Replace with your target region

      - name: Verify AWS Authentication
        run: |
          aws sts get-caller-identity

      - name: List AWS S3 Buckets
        run: |
          aws s3 ls
