name: Demo Git Hub Action WorkFlow
on: workflow_dispatch
jobs:
  Introduction:
      runs-on: ubuntu-latest
      steps:
        - name: Greetings
          run: echo "Hellow World"

        - name: Generate Greeting
          id: greet_step
          run: echo "messege=Hellow_Sourav" >> $GITHUB_OUTPUT

        - name: Use Greeting
          run: echo "The messege was ${{ steps.greet_step.outputs.messege }}"

  Variable_Demo:
      needs: Introduction
      env:
        dept: "Engineering"
      runs-on: ubuntu-latest
      steps:
        - name: printing variable values
          run: echo "My Depertment is $dept"
