name: Environment Demo GitHub Action
on: workflow_dispatch
jobs:
  prod_deploy:
     runs-on: ubuntu-latest
     environment: Production
     steps:
       - name: deploy
         run: echo "Deploying to environment - $env"

  Stage_deploy:
     runs-on: ubuntu-latest
     environment: Staging
     steps:
       - name: deploy
         run: echo "Deploying to environment - $env"


  test_deploy:
     runs-on: ubuntu-latest
     environment: Testing
     steps:
       - name: deploy
         run: echo "Deploying to environment - $env"
