name: Spring App Local Artifact Build And Image Build Push Demo
on: workflow_dispatch

jobs:
  build_and_push:
      runs-on: ${{ matrix.os }}
      strategy:
          matrix:
            os: [ubuntu-latest,windows-2025]
      steps:
        - name: Code CheckOut
          uses: actions/checkout@v4

        - name: Build Artifact
          run: mvn -DskipTests clean install

        - name: Run Docker login
          run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build Docker Image
          run: docker build -t spc:0.1 .

        - name: Print docker images
          run: docker image ls

        - name: Running an SPC docker instance
          run: docker run -d --name spc-pet -p 8888:8080 spc:0.1

        - name: Print Docker Instances
          run: docker ps

        - name: Print Ip
          run: ip r
