name: demo-spc-build-workflow
on: [workflow_dispatch]
jobs:
  say-hello:
      runs-on: ubuntu-latest
      steps:
        - name: Greetings
          run: echo "Hellow World"
   
  Code_build:
    runs-on: ubuntu-latest
    steps:
      - name: getting the Code
        uses: actions/checkout@v4

      - name: Code Analysis
        run: mvn test
      
      - name: install the Code
        run: mvn install

      - name: Build The Code
        run: mvn package

      - name: Upload The Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-build-output
          path: dist

