name: demo spring app github action workflow
on: workflow_dispatch

jobs:
  build-and-test:
       runs-on: ubuntu-latest
       steps:
          - name: checkout code
            uses: actions/checkout@v4
        
          - name: build code
            run: mvn install

          - name: test code
            run: mvn test
