name: Matrix Test Example
on: workflow_dispatch

jobs:
   deploy:   
      runs-on: ${{ matrix.os }}
      strategy:
          matrix:
            node-version: [18, 20, 22]
            os: [ubuntu-latest, windows-latest]

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: SetUp Node.js
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}
