name: spc build and push
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SPC Image Build
        run: docker build -t spc:0.1 .
