name: CI Code PipeLine
on:
 push:
   branches:
     - main
   paths-ignore:
     - 'src/**'
 issues:
    types: [opened, labeled]



jobs:
  Greetings_Job:
        runs-on: ubuntu-latest
        steps:
          - name: Greetings
            run: |
              echo "Good Evening"
    
  Triage:
      runs-on: ubuntu-latest
      steps:
        - name: Process-issue
          run: |
            echo "An Issue was created"
            echo "Action Type: ${{ github.event.action }}"
